---
packages:
- name: go_1.5.3
  version: !binary |-
    YThjNjZlNzIwNWExODQ1ZDM3ZmY5NGJlNThkYjQ0ODlkNmMyODY0NQ==
  fingerprint: !binary |-
    YThjNjZlNzIwNWExODQ1ZDM3ZmY5NGJlNThkYjQ0ODlkNmMyODY0NQ==
  sha1: !binary |-
    OWM1NDI4ZWZjMDUyYzkwODMwOTA4MjA2M2NmMjQ3NTU0MzkwMDkxZA==
  dependencies: []
- name: timer
  version: !binary |-
    M2JmMTJhNTdhZWQ3NWQ5MjQ2ZDgwOTk2MzlhOGRmOGQ2NGI1YWY1OA==
  fingerprint: !binary |-
    M2JmMTJhNTdhZWQ3NWQ5MjQ2ZDgwOTk2MzlhOGRmOGQ2NGI1YWY1OA==
  sha1: !binary |-
    MDE0YmI1NGViNzFjMjFjMDAxMDE0YjgxODEwMzBlYTlhM2FiMDhiMg==
  dependencies:
  - go_1.5.3
jobs:
- name: timer_job
  version: !binary |-
    NDE5NmVjMjE4ZGViOGYyY2U1Y2Y0YTE3OGM3NWZiNWQwNmNjYjQ4ZQ==
  fingerprint: !binary |-
    NDE5NmVjMjE4ZGViOGYyY2U1Y2Y0YTE3OGM3NWZiNWQwNmNjYjQ4ZQ==
  sha1: !binary |-
    ODU1YzY4NzM0ZDIwODNhMWUzNjg0MmZjNjI0NzdkYjQyM2UzM2MxMg==
commit_hash: '00000000'
uncommitted_changes: false
name: timer_dev
version: 0+dev.19
